###
POST http://localhost:3100/api/v1/users/new-user HTTP/1.1
Content-Type: application/json

{
    "firstname": "test2",
    "lastname": "test2",
    "email": "test2@test.com",
    "current_password": "user123"
}

###
GET http://localhost:3100/api/v1/users HTTP/1.1

###
GET http://localhost:3100/api/v1/users/6511effdb7515f0d4a7f524c HTTP/1.1

###
PATCH http://localhost:3100/api/v1/users/6511effdb7515f0d4a7f524c HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test 2",
    "lastname": "Test 2 lastname"
}

###
PUT http://localhost:3100/api/v1/users/6511effdb7515f0d4a7f524c HTTP/1.1
Content-Type: application/json

{
    "firstname": "Test 2 v2",
    "lastname": "Test 2 lastname v2"
}

###
DELETE http://localhost:3100/api/v1/users/6511effdb7515f0d4a7f524c HTTP/1.1



//////////////////////////////////////////////////////

###
POST http://localhost:3100/api/v1/auth/signin HTTP/1.1
Content-Type: application/json

{
    "firstname": "test",
    "lastname": "test",
    "email": "test15@test.com",
    "current_password": "user123"
}

###
POST http://localhost:3100/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "TEST14@test.com",
    "current_password": "user123"
}

###
GET http://localhost:3100/api/v1/auth/get-me/6536da21809af33e73eafd6d HTTP/1.1




